### ISSUE TITLE
View the keypoints marked by the ‘magic_point’ model on my dataset

### ISSUE THREAD

**Issue by yanhuanhuanyy** [rpautrat/SuperPoint#104]
Hi, @rpautrat ,I want to view the keypoints marked by the 'magic_point' model on my dataset and check if these keypoints are marked in the correct position I defined. 
So, I follow your step 1 Training Magicpoint on Synthetic Shapes.  To adapt step 2 to my own dataset, I take your advice in #100. I copy the file datasets/coco.py (let's call it datasets/my_dataset) and modify it to adapt it to my own dataset. Then I modify the config file configs/magic_point_coco_export.yaml and replace the line name: 'coco' by name: 'my_dataset'. I use this config file in step 2 and it works.

To evaluate detector_repeatability(detector_repeatability_coco.ipynb):
Firstly, I modify the config file coco_patches_generation.yaml (change resize) and the file generate_coco_patches.py (replace the name: 'coco' by name: 'my_dataset'), using the command python generate_coco_patches.py configs/coco_patches_generation.yaml to generate my dataset patches. 
Secondly, I modify configs/magic-point_repeatability.yaml and replace the dataset entry by 'my_dataset', use False for 'resize' and use  'magic_point' model. But,when executing the script of 'python export_detections_repeatability.py configs/magic-point_repeatability.yaml magic-point_synth --export_name=magicpoint_my_dataset-repeat', error occurred:

-----------------------------------------------------------------------
export_detections_repeatability.py:23: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
[08/31/2019 11:56:02 INFO] Number of GPUs detected: 1
2019-08-31 11:56:04.650065: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-08-31 11:56:05.079396: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:84:00.0
totalMemory: 11.90GiB freeMemory: 283.94MiB
2019-08-31 11:56:05.079437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2019-08-31 11:56:05.513300: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-31 11:56:05.513334: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 
2019-08-31 11:56:05.513340: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N 
2019-08-31 11:56:05.513524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:84:00.0, compute capability: 6.1)
[08/31/2019 11:56:05 INFO] Scale of 0 disables regularizer.
[08/31/2019 11:56:05 INFO] Scale of 0 disables regularizer.
[08/31/2019 11:56:05 INFO] Scale of 0 disables regularizer.
[08/31/2019 11:56:05 INFO] Scale of 0 disables regularizer.
[08/31/2019 11:56:05 INFO] Scale of 0 disables regularizer.
[08/31/2019 11:56:05 INFO] Scale of 0 disables regularizer.
[08/31/2019 11:56:05 INFO] Scale of 0 disables regularizer.
[08/31/2019 11:56:05 INFO] Scale of 0 disables regularizer.
[08/31/2019 11:56:05 INFO] Scale of 0 disables regularizer.
[08/31/2019 11:56:05 INFO] Scale of 0 disables regularizer.
2019-08-31 11:56:05.940393: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2019-08-31 11:56:05.940446: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-31 11:56:05.940455: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 
2019-08-31 11:56:05.940460: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N 
2019-08-31 11:56:05.941674: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:84:00.0, compute capability: 6.1)
[08/31/2019 11:56:06 INFO] Restoring parameters from /public/Yanhuanhuan/SuperPoint-master_us/superpoint/exper_dir/magic-point_synth/model.ckpt-40000
  0%|                                                  | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
File "/public/Yanhuanhuan/yhhenvs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call 
     return fn(*args)
File "/public/Yanhuanhuan/yhhenvs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
File "/public/Yanhuanhuan/yhhenvs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: pyfunc_4 returns 0 values, but expects to see 1 values. 
     [[Node: PyFunc = PyFunc[Tin=[DT_STRING], Tout=[DT_UINT8], token="pyfunc_4", _device="/device:CPU:0"](arg0)]] 
     [[Node: IteratorGetNext_2 = IteratorGetNext[output_shapes=[[3,3], [?,?,1], [?,?,1]], output_types=[DT_DOUBLE, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_2)]]

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "export_detections_repeatability.py", line 42, in <module>
    data = next(test_set)
File "/public/Yanhuanhuan/SuperPoint-master_us/superpoint/datasets/base_dataset.py", line 115, in _get_set_generator
    yield self.sess.run(self.tf_next[set_name])
File "/public/Yanhuanhuan/yhhenvs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run 
    run_metadata_ptr)
File "/public/Yanhuanhuan/yhhenvs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
File "/public/Yanhuanhuan/yhhenvs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run 
    run_metadata)
File "/public/Yanhuanhuan/yhhenvs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call 
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: pyfunc_4 returns 0 values, but expects to see 1 values.	 
     [[Node: PyFunc = PyFunc[Tin=[DT_STRING], Tout=[DT_UINT8], token="pyfunc_4", _device="/device:CPU:0"](arg0)]]	 
     [[Node: IteratorGetNext_2 = IteratorGetNext[output_shapes=[[3,3], [?,?,1], [?,?,1]], output_types=[DT_DOUBLE, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_2)]]

-----------------------------------------------------------------------

What's wrong? Could you give me some help? Thank you.

**Comment by rpautrat** [comment]
It means that the test_set mentioned in the code is empty. You need to modify the file `datasets/patches_dataset.py` as well and adapt it to your own dataset. Because currently it can only work with COCO or HPatches.

**Comment by yanhuanhuanyy** [comment]
Thanks a million!!  It works! I still have a small question about visualize_coco_adaptation-iterations .ipynb. I don't know how to do these experiment [
'mp_synth-v6_photo-hom-aug_ha1-100-3-old_coco',
  'mp_synth-v5_aug_reg-001_estop-60000_coco',
#    'mp_synth-v5_aug_reg-001_estop-60000_ha1-100-3_coco',
    'mp_synth-v6_photo-hom-aug_ha1-100-3-old_coco',
    'mp_synth-v6_photo-hom-aug_ha1-100-0-persp_coco',
#    'mp_synth-v5_aug_reg-001_estop-60000_ha1-1000-10_coco',
]
I just want to view the keypoints marked by the 'No adaptation' case and 'Adaptation N=100' case . I’m grateful for your help.

**Comment by yanhuanhuanyy** [comment]
Thanks a million!!  It works! I still have a small question about visualize_coco_adaptation-iterations .ipynb. I don't know how to do these experiment [
![TIM图片20190901170610](https://user-images.githubusercontent.com/36001989/64074187-d598ab80-ccda-11e9-827c-ad62eab25ef8.png)
]
I just want to view the keypoints marked by the 'No adaptation' case and 'Adaptation N=100' case . I’m grateful for your help~~

**Comment by rpautrat** [comment]
Those are just the export of the pseudo ground truth on COCO that you create with `export_detections.py`. Change the parameter 'homography_adaptation->num' to 0 or 100 in `magic-point_coco_export.yaml` to switch between 'No adaptation' and 'Adaptation N=100'.

**Comment by zxp771** [comment]
Hi @yanhuanhuanyy 

Have you modified the magic-point.py for adapting your dataset?

**Comment by yanhuanhuanyy** [comment]
Ok, Many thanks for your reply. @rpautrat

**Comment by yanhuanhuanyy** [comment]
@zxp771  No, I haven't. I've been busy lately.  If I have time, I will try to modify the magic-point.py.
