### ISSUE TITLE
Error for Training MagicPoint

### ISSUE THREAD

**Issue by ufukefe** [rpautrat/SuperPoint#129]
Hello, thanks for sharing your great work!
I want to train the network but have following error. What can be the reason?

python experiment.py train configs/magic-point_shapes.yaml magic-point_synth

experiment.py:142: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
[12/27/2019 15:37:50 INFO] Running command TRAIN
[12/27/2019 15:37:50 INFO] Number of GPUs detected: 1
Traceback (most recent call last):
  File "experiment.py", line 149, in <module>
    args.func(config, output_dir, args)
  File "experiment.py", line 87, in _cli_train
    train(config, config['train_iter'], output_dir)
  File "experiment.py", line 21, in train
    with _init_graph(config) as net:
  File "/home/ufuk/anaconda3/envs/superpoint4/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "experiment.py", line 69, in _init_graph
    dataset = get_dataset(config['data']['name'])(**config['data'])
  File "/home/ufuk/Desktop/MMI 727 - DEEP LEARNING/Project/SuperPoint-master_with_pre_trained/SuperPoint-master/superpoint/datasets/base_dataset.py", line 102, in __init__
    self.dataset = self._init_dataset(**self.config)
  File "/home/ufuk/Desktop/MMI 727 - DEEP LEARNING/Project/SuperPoint-master_with_pre_trained/SuperPoint-master/superpoint/datasets/synthetic_shapes.py", line 126, in _init_dataset
    self.dump_primitive_data(primitive, tar_path, config)
  File "/home/ufuk/Desktop/MMI 727 - DEEP LEARNING/Project/SuperPoint-master_with_pre_trained/SuperPoint-master/superpoint/datasets/synthetic_shapes.py", line 71, in dump_primitive_data
    temp_dir = Path(os.environ['TMPDIR'], primitive)
  File "/home/ufuk/anaconda3/envs/superpoint4/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'TMPDIR'

**Comment by rpautrat** [comment]
Hi, have a look at this comment of a previous issue: https://github.com/rpautrat/SuperPoint/issues/21#issuecomment-443630987

**Comment by ufukefe** [comment]
Thank you for fast response, it solved the issue :)
