### ISSUE TITLE
KeyError: 'NonMaxSuppressionV3' for Demo 'matching-features-demo-with-pretrained-weights'

### ISSUE THREAD

**Issue by tik0** [rpautrat/SuperPoint#138]
I've followed your installation instruction and try to run this example: https://github.com/rpautrat/SuperPoint#matching-features-demo-with-pretrained-weights

I use Ubuntu 16.04 with pyenv and python 3.6.1 in a virtual environment.
The only difference is, that I use `tensorflow==1.6` instead of `tensorflow-gpu==1.6`.
Unfortunately, I get a `KeyError: 'NonMaxSuppressionV3'`. Here is the full backtrace:

```
bash> python match_features_demo.py sp_v6 /opt/python_virtual_env/SuperPoint/DATA_DIR/HPatches/i_pool/1.ppm /opt/python_virtual_env/SuperPoint/DATA_DIR/HPatches/i_pool/6.ppm
...
Traceback (most recent call last):
  File "match_features_demo.py", line 115, in <module>
    str(weights_dir))
  File "/opt/repositories/pyenv/versions/SuperPoint/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 216, in load
    saver = tf_saver.import_meta_graph(meta_graph_def_to_load, **saver_kwargs)
  File "/opt/repositories/pyenv/versions/SuperPoint/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1909, in import_meta_graph
    **kwargs)
  File "/opt/repositories/pyenv/versions/SuperPoint/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 737, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/opt/repositories/pyenv/versions/SuperPoint/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/opt/repositories/pyenv/versions/SuperPoint/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 431, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "/opt/repositories/pyenv/versions/SuperPoint/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 211, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: 'NonMaxSuppressionV3'
```

Here are all installed packages:

```
bash> pip freeze
absl-py==0.9.0
astor==0.8.1
attrs==19.3.0
backcall==0.1.0
bleach==1.5.0
decorator==4.4.1
defusedxml==0.6.0
entrypoints==0.3
flake8==3.7.9
gast==0.3.3
grpcio==1.26.0
html5lib==0.9999999
importlib-metadata==1.5.0
ipykernel==5.1.4
ipython==7.12.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.16.0
Jinja2==2.11.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.1.0
jupyter-core==4.6.1
Markdown==3.1.1
MarkupSafe==1.1.1
mccabe==0.6.1
mistune==0.8.4
nbconvert==5.6.1
nbformat==5.0.4
notebook==6.0.3
numpy==1.18.1
opencv-contrib-python==3.4.2.16
opencv-python==3.4.2.16
pandocfilters==1.4.2
parso==0.6.1
pexpect==4.8.0
pickleshare==0.7.5
prometheus-client==0.7.1
prompt-toolkit==3.0.3
protobuf==3.11.3
ptyprocess==0.6.0
pycodestyle==2.5.0
pyflakes==2.1.1
Pygments==2.5.2
pyrsistent==0.15.7
python-dateutil==2.8.1
PyYAML==5.3
pyzmq==18.1.1
qtconsole==4.6.0
scipy==1.4.1
Send2Trash==1.5.0
six==1.14.0
-e git+https://github.com/rpautrat/SuperPoint.git@8dd6efc6f7482f533eaa86a6aaac13cfd44fdd2c#egg=superpoint
tensorboard==1.6.0
tensorflow==1.6.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.3
tqdm==4.42.1
traitlets==4.3.3
wcwidth==0.1.8
Werkzeug==0.16.1
widgetsnbextension==3.5.1
zipp==2.1.0
```

I already tried to install different tensorflow versions, but without any effect.
Any idea?

**Comment by robertLiuLinFeng** [comment]
Hello, I encountered the same problem with you, did you finally solve this problem?

**Comment by rpautrat** [comment]
Hi,

I think the reason why you got this error was that that I exported the model in a more recent version of Tensorflow. I have just pushed new trained weights, that should work in TF 1.6 this time.

Let me know if this didn't solve your issue.

**Comment by tik0** [comment]
It works like a charm! Thank you very much for your fast support!
