### ISSUE TITLE
error when create synthetic_shapes dataset 

### ISSUE THREAD

**Issue by 904281665** [rpautrat/SuperPoint#158]
Sorry to bother pulling， I get an error when I train magic point at step 1.
the code is broken by this error, when create the checkerboard:

BrokenPipeError: Broken pipe:

[07/28/2020 16:29:49 INFO] Extracting archive for primitive draw_lines.
[07/28/2020 16:29:51 INFO] Extracting archive for primitive draw_polygon.
[07/28/2020 16:29:54 INFO] Extracting archive for primitive draw_multiple_polygons.
[07/28/2020 16:29:57 INFO] Extracting archive for primitive draw_ellipses.
[07/28/2020 16:30:00 INFO] Extracting archive for primitive draw_star.
[07/28/2020 16:30:04 INFO] Generating tarfile for primitive draw_checkerboard.
                                                                   Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1149, in __iter__
    self.refresh(lock_args=self.lock_args)
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1339, in refresh
    self.display()
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1472, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 305, in print_status
    fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 298, in fp_write
    fp.write(_unicode(s))
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "experiment.py", line 148, in <module>
    args.func(config, output_dir, args)
  File "experiment.py", line 86, in _cli_train
    train(config, config['train_iter'], output_dir)
  File "experiment.py", line 21, in train
    with _init_graph(config) as net:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "experiment.py", line 68, in _init_graph
    dataset = get_dataset(config['data']['name'])(**config['data'])
  File "/home/dongshichao/my_job/SuperPoint/superpoint/datasets/base_dataset.py", line 102, in __init__
    self.dataset = self._init_dataset(**self.config)
  File "/home/dongshichao/my_job/SuperPoint/superpoint/datasets/synthetic_shapes.py", line 126, in _init_dataset
    self.dump_primitive_data(primitive, tar_path, config)
  File "/home/dongshichao/my_job/SuperPoint/superpoint/datasets/synthetic_shapes.py", line 81, in dump_primitive_data
    for i in tqdm(range(size), desc=split, leave=False):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1183, in __iter__
    self.close()
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1298, in close
    if self.display(msg='', pos=pos) and not pos:
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1472, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 305, in print_status
    fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 298, in fp_write
    fp.write(_unicode(s))
BrokenPipeError: [Errno 32] Broken pipe

**Comment by rpautrat** [comment]
Hi, did you try running the code again after this? It looks like a temporary lost connection with a cluster/distant computer.

**Comment by 904281665** [comment]
I tried many times, but still not working.Can I generate data without a GPU?Do you have the generated data available for me to download?Many thanks！

**Comment by rpautrat** [comment]
That's weird..
In the current version, you need a GPU to run the code, even though it is actually not needed to extract the synthetic data. You can download the synthetic shapes [here](https://www.polybox.ethz.ch/index.php/s/5DDt4gVqsoDdPeQ) instead.

**Comment by 904281665** [comment]
Many thanks!

**Comment by 904281665** [comment]
problem solved
