### ISSUE TITLE
Recall and Precision

### ISSUE THREAD

**Issue by zt-Github-1** [rpautrat/SuperPoint#175]
Hi！
What should I do to make the program output accurate values of recall and precision?

**Comment by rpautrat** [comment]
Hi,
You would need to introduce a tolerance threshold of 2-3 pixels to consider a point as correctly identified when it is close enough to a label. And then for every predicted point check if there is a ground truth point next to it, and make sure that each ground truth point can be matched to only one predicted point.
Running this procedure is a bit slow, and that's why we currently compute a coarse precision and recall during training to save time.

**Comment by zt-Github-1** [comment]
Thank you very much for your answer！
I have another question to ask you. When I use "python3 export_detections.py configs/magic-point_coco_export.yaml magic-point_synth --pred_only --batch_size=5 --export_name=magic-point_coco-export1" to performing self-supervised training, the program prompts 
[11/03/2020 14:33:19 INFO] Number of GPUs detected: 1
[11/03/2020 14:33:24 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:24 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:24 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:24 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:24 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:24 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:24 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:24 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:24 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:24 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:25 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:25 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:25 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:25 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:25 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:25 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:25 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:25 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:25 INFO] Scale of 0 disables regularizer.
[11/03/2020 14:33:25 INFO] Scale of 0 disables regularizer.
Traceback (most recent call last):
  File "export_detections.py", line 40, in <module>
    net.load(str(checkpoint))
  File "/home/zt/Desktop/SuperPoint-masterFU(save)/superpoint/models/base_model.py", line 396, in load
    raise ValueError('Checkpoint directory is empty.')
ValueError: Checkpoint directory is empty.
Is this "Checkpoint directory" generated by the program itself or needs to be created manually? What is the content inside?

**Comment by rpautrat** [comment]
Hi,
The checkpoint directory should have been created by Step 1 in the Readme, a folder named `magic-point_synth` in your `EXP_PATH`. Did you correctly execute step 1?

**Comment by zt-Github-1** [comment]
I tried step 1 on my computer several times, but I don’t know if the computer’s configuration is not enough for training. As a result, the system gets stuck every time iterates to about 45,000 times. Can I reduce the number of training sessions? Will this affect the result?

**Comment by rpautrat** [comment]
That's weird, training for 45000 or 50000 iterations shouldn't make a difference for your computer. But anyway, training it for 45000 iterations or a bit less should be enough. The model usually converges after 40000 to 50000 iterations.

**Comment by zt-Github-1** [comment]
Thank you for your reply, I will try again.

**Comment by zt-Github-1** [comment]
Hello, I have completed steps one and two. 
But when I use "python3 Experiment.py train configs / magic-point_coco_train.yaml magic-point_coco to go to MagicPoint training on MS-COCO", the following error is prompted:
Assertion error: image 7575 has no corresponding label /home/zt/save/experpath/outputs/mp_synth-v10_ha2-100/7575.npz

However, when I removed the suggested image from magic-point_coco-export1 and the output folder, it prompted that other images did not have corresponding labels. Is there any reason for the training in the first two steps? Maybe this result has something to do with the type or size of the datasets I use? In fact, I did not use the standard COCO data set because it is too big.

**Comment by rpautrat** [comment]
How did you limit the size of COCO? Currently the training code takes all the images in the folder `$DATA_PATH/COCO/train2014/`, so if you didn't export all the labels for the images in this directory, it makes sense that it cannot find the labels.
The right way to limit the number of images in COCO would be to use the parameter 'truncate' in the config file.

**Comment by zt-Github-1** [comment]
Thanks for your help, I successfully ran the first three steps. 
 But when I evaluated, that is the fourth step, I got an error from the program:

[11/04/2020 14:54:49 INFO] Number of GPUs detected: 1
Traceback (most recent call last):
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1628, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 2 but is rank 0 for 'matmul_1' (op: 'MatMul') with input shapes: [3,3], [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export_detections_repeatability.py", line 33, in <module>
    with experiment._init_graph(config, with_dataset=True) as (net, dataset):
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/zt/Desktop/SuperPoint-masterFU(save)/superpoint/experiment.py", line 71, in _init_graph
    dataset = get_dataset(config['data']['name'])(**config['data'])
  File "/home/zt/Desktop/SuperPoint-masterFU(save)/superpoint/datasets/base_dataset.py", line 108, in __init__
    self.tf_splits[n] = self._get_data(self.dataset, n, **self.config)
  File "/home/zt/Desktop/SuperPoint-masterFU(save)/superpoint/datasets/patches_dataset.py", line 110, in _get_data
    homographies = homographies.map(_adapt_homography_to_preprocessing)
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1038, in map
    return MapDataset(self, map_func)
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2611, in __init__
    map_func, "Dataset.map()", input_dataset)
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1860, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 479, in add_to_graph
    self._create_definition_if_needed()
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 335, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 344, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 864, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1794, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "/home/zt/Desktop/SuperPoint-masterFU(save)/superpoint/datasets/patches_dataset.py", line 91, in _adapt_homography_to_preprocessing
    H = warped_translation @ down_scale @ H @ up_scale @ translation
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 866, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 2057, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4560, in mat_mul
    name=name)
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 738, in create_op
    **kwargs)
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1792, in __init__
    control_input_ops)
  File "/home/zt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 2 but is rank 0 for 'matmul_1' (op: 'MatMul') with input shapes: [3,3], [].

This looks like there was a problem when calculating the matrix calculation, but I did not modify the .py file related to the homography matrix.

**Comment by rpautrat** [comment]
The error seems to come from [line 91](https://github.com/rpautrat/SuperPoint/blob/61bc16ff0e096340a26feb4cf80bf6b4bacee267/superpoint/datasets/patches_dataset.py#L91) of the file `datasets/patches_dataset.py`. It complains that the right operand of matrix multiplication with H is empty (size [ ]). This doesn't happen on my side, so not sure why it occurs for you...

Are you sure that the HPatches dataset is correctly loaded? For example that the paths are all correct and the images in the right location?

**Comment by zt-Github-1** [comment]
Thank you for your reply. I spent some time adjusting the path and saving format related to HPatches. Now the program is working normally. 
But I still have some questions. If the above steps are all trained using my own datasets, is the model that is suitable for this datasets? Where is this model stored? Where should I call it when I want to use this model for feature point extraction and matching?

**Comment by rpautrat** [comment]
You mean if you train on your dataset, can you still evaluate your model on HPatches? Since HPatches is a quite generic benchmark for features, I would say yes. It is quite diverse, with its split between viewpoint and illumination changes.

The model you trained is stored in `$EXPER_PATH/<exp_name>`. You can find an example of how to use the trained model to perform keypoint detection and description in `superpoint/match_features_demo.py`. Note that this script is using the tensorflow saved model, which can be obtained using `superpoint/export_model.py`. The pretrained model available in [pretrained_models](https://github.com/rpautrat/SuperPoint/tree/master/pretrained_models) is one such saved model for example.

**Comment by zt-Github-1** [comment]
Thanks a lot. I will try again under your guidance.
