### ISSUE TITLE
The Problem about Training MagicPoint on Synthetic Shapes

### ISSUE THREAD

**Issue by gx0522** [rpautrat/SuperPoint#183]
Hi,when I runned the step1，there was the error that the system don't find the document  
Traceback (most recent call last):
  File "experiment.py", line 145, in <module>
    with capture_outputs(os.path.join(output_dir, 'log')):
  File "C:\Users\GX\Anaconda3\envs\superpoints\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "E:\PycharmProject\SuperPoint\superpoint\utils\stdout_capturing.py", line 44, in capture_outputs
    stdin=subprocess.PIPE, stderr=target_fd, stdout=1)
  File "C:\Users\GX\Anaconda3\envs\superpoints\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Users\GX\Anaconda3\envs\superpoints\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)

Could you share the synthetic shapes dataset with me?my email 459356282@qq.com
Thank you very much

**Comment by rpautrat** [comment]
Hi, you did not put the entire error message, so I cannot help you there.

But if you can't run the code, there is no point in sending you the dataset, since you will not be able to run the training afterwards anyway. You should first solve your issue.

And the dataset is a bit heavy to transfer online, that's why it is easier if you can directly generate it on your machine.

**Comment by gx0522** [comment]
Thanks，
whether the code need to run in linux system and which version of tf is used?
my system is window10,the version of tf is 2.4。
Now I have a problem that module 'tensorflow.python.framework.ops' has no attribute 'RegisterShape'
 
(superpoints) PS E:\PycharmProject\SuperPoint\superpoint> python experiment.py train configs/magic-point_shapes.yaml magic-point_synth
2020-12-15 20:29:25.749855: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2020-12-15 20:29:25.749961: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
experiment.py:144: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
[12/15/2020 20:29:27 INFO] Running command TRAIN
[12/15/2020 20:29:27 INFO] Number of GPUs detected: 0
Traceback (most recent call last):
  File "experiment.py", line 152, in <module>
    args.func(config, output_dir, args)
  File "experiment.py", line 89, in _cli_train
    train(config, config['train_iter'], output_dir)
  File "experiment.py", line 22, in train
    with _init_graph(config) as net:
  File "C:\Users\GX\Anaconda3\envs\superpoints\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "experiment.py", line 71, in _init_graph
    dataset = get_dataset(config['data']['name'])(**config['data'])
  File "E:\PycharmProject\SuperPoint\superpoint\datasets\__init__.py", line 2, in get_dataset
    mod = __import__('datasets.{}'.format(name), fromlist=[''])
  File "E:\PycharmProject\SuperPoint\superpoint\datasets\synthetic_shapes.py", line 12, in <module>
    from .utils import pipeline
  File "E:\PycharmProject\SuperPoint\superpoint\datasets\utils\pipeline.py", line 6, in <module>
    from models.homographies import (sample_homography, compute_valid_mask,
  File "E:\PycharmProject\SuperPoint\superpoint\models\homographies.py", line 2, in <module>
    from tensorflow.contrib.image import transform as H_transform
  File "C:\Users\GX\Anaconda3\envs\superpoints\lib\site-packages\tensorflow\contrib\__init__.py", line 40, in <module>
    from tensorflow.contrib import coder
  File "C:\Users\GX\Anaconda3\envs\superpoints\lib\site-packages\tensorflow\contrib\coder\__init__.py", line 22, in <module>
    from tensorflow.contrib.coder.python.ops.coder_ops import *
  File "C:\Users\GX\Anaconda3\envs\superpoints\lib\site-packages\tensorflow\contrib\coder\python\ops\coder_ops.py", line 22, in <module>
    from tensorflow.contrib.coder.python.ops import gen_coder_ops
  File "C:\Users\GX\Anaconda3\envs\superpoints\lib\site-packages\tensorflow\contrib\coder\python\ops\gen_coder_ops.py", line 99, in <module>
    _ops.RegisterShape("PmfToQuantizedCdf")(None)
AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'RegisterShape'

**Comment by rpautrat** [comment]
Hi, this code has been written to be used on Linux indeed. It could work on Windows, but I cannot bring support for that, I am not familiar enough with Windows.

TF 2.4 is a too recent version. This code can only be used with older versions of TF (e.g. TF 1.12). You can follow the configuration described in https://github.com/rpautrat/SuperPoint/issues/173, this has been proven to work correctly.

**Comment by gx0522** [comment]
Thank you very much。I will try again

**Comment by alexlorenzo** [comment]
Hello @gx0522, I used WSL2 on Windows and a Docker with Tensorflow 1.12 and worked perfectly well on my machine.
(https://docs.docker.com/docker-for-windows/wsl/)

**Comment by gx0522** [comment]
> 
> 
> Hello @gx0522, I used WSL2 on Windows and a Docker with Tensorflow 1.12 and worked perfectly well on my machine.
> (https://docs.docker.com/docker-for-windows/wsl/)

Thank you very much，I will take a try by
