### ISSUE TITLE
problem of running 'match_features_demo.py'

### ISSUE THREAD

**Issue by Zhaoyue628** [rpautrat/SuperPoint#201]
Hello，rpautrat, sorry to disturb you. When running 'match_features_demo.py', I encountered the following error.This error confuse me a long time, so could you give me some suggestion? 

(new_tensorflow) cczu402@server402:~/SuperPoint-master/superpoint$ python match_features_demo.py sp_v6 DATA_DIR/HPatches/i_ajuntament/1.ppm DATA_DIR/HPatches/i_ajuntament/2.ppm
2021-04-05 09:26:46.866803: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2021-04-05 09:26:46.965334: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-05 09:26:46.966005: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce RTX 3090 major: 8 minor: 6 memoryClockRate(GHz): 1.695
pciBusID: 0000:01:00.0
totalMemory: 23.70GiB freeMemory: 23.22GiB
2021-04-05 09:26:46.966017: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2021-04-05 09:29:18.040427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-04-05 09:29:18.040445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2021-04-05 09:29:18.040450: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2021-04-05 09:29:18.040506: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2021-04-05 09:29:18.040524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 22508 MB memory) -> physical GPU (device: 0, name: GeForce RTX 3090, pci bus id: 0000:01:00.0, compute capability: 8.6)

Traceback (most recent call last):
  File "match_features_demo.py", line 138, in <module>
    m_kp1, m_kp2, matches = match_descriptors(kp1, desc1, kp2, desc2)
  File "match_features_demo.py", line 49, in match_descriptors
    matches = bf.match(desc1, desc2)
cv2.error: OpenCV(3.4.2) /io/opencv/modules/core/src/batch_distance.cpp:265: error: (-215:Assertion failed) K == 1 && update == 0 && mask.empty() in function 'batchDistance'

Thanks in advance!

**Comment by rpautrat** [comment]
Hi,
That's an interesting error, I have never seen that. Did you try printing the number of keypoints and descriptors when it happens? Does it happen all the time or for this pair of images only? Does it still appear if you use `crossCheck=False` on [line 48](https://github.com/rpautrat/SuperPoint/blob/313a0a115961bc2a98a5ed1d7bde33fa99542398/superpoint/match_features_demo.py#L48)?

**Comment by Zhaoyue628** [comment]
Thank you for your reply.
I haven’t try to print the number of keypoints and descriptors when it happen. I will try it as you suggested.It happens all the time,not only for this pair of images. I have tried to use ‘crossCheck=False’, but it will return the following error:

Traceback (most recent call last):
  File "match_features_demo.py", line 139, in <module>
    H, inliers = compute_homography(m_kp1, m_kp2)
  File "match_features_demo.py", line 63, in compute_homography
    H, inliers = cv2.findHomography(matched_pts1[:, [1, 0]],
TypeError: tuple indices must be integers or slices, not tuple

I haven’t try to print the number of keypoints and descriptors when it happen. I will try it as you suggested.

**Comment by xushangnjlh** [comment]
@Zhaoyue628  I also encountered this problem, have you soleved this?
