### ISSUE TITLE
UnimplementedError: Cast string to float is not supported

### ISSUE THREAD

**Issue by 1962975362** [rpautrat/SuperPoint#223]
[07/15/2021 17:03:56 INFO] Restoring parameters from /home/ninghua/data/1/liyafeng/SuperPoint/output/magic-point_coco/model/last.ckpt-18000
  0%|          | 0/1000 [00:00<?, ?it/s]2021-07-15 17:03:57.341972: W tensorflow/core/framework/op_kernel.cc:1250] OP_REQUIRES failed at cast_op.cc:123 : Unimplemented: Cast string to float is not supported
2021-07-15 17:03:57.342041: E tensorflow/core/common_runtime/executor.cc:623] Executor failed to create kernel. Unimplemented: Cast string to float is not supported
	 [[{{node Cast}} = Cast[DstT=DT_FLOAT, SrcT=DT_STRING, Truncate=false, _device="/device:CPU:0"](arg0)]]
2021-07-15 17:03:57.342237: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at iterator_ops.cc:947 : Unimplemented: Cast string to float is not supported
	 [[{{node Cast}} = Cast[DstT=DT_FLOAT, SrcT=DT_STRING, Truncate=false, _device="/device:CPU:0"](arg0)]]
Traceback (most recent call last):
  File "/home/yafeng/anaconda3/envs/SuperPoint/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/yafeng/anaconda3/envs/SuperPoint/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/yafeng/anaconda3/envs/SuperPoint/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnimplementedError: Cast string to float is not supported
	 [[{{node Cast}} = Cast[DstT=DT_FLOAT, SrcT=DT_STRING, Truncate=false, _device="/device:CPU:0"](arg0)]]
	 [[{{node OneShotIterator_2}} = OneShotIterator[container="", dataset_factory=_make_dataset_qitaVLF1Dtw[], output_shapes=[[3,3], [?,?,1], [?,?,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], shared_name="", _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/yafeng/anaconda3/envs/SuperPoint/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/yafeng/Projects/SuperPoint/superpoint/experiment.py", line 81, in _init_graph
    yield model, dataset
  File "/home/yafeng/Projects/SuperPoint/superpoint/export_detections_repeatability.py", line 42, in <module>
    data = next(test_set)
  File "/home/yafeng/Projects/SuperPoint/superpoint/datasets/base_dataset.py", line 115, in _get_set_generator
    yield self.sess.run(self.tf_next[set_name])
  File "/home/yafeng/anaconda3/envs/SuperPoint/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/yafeng/anaconda3/envs/SuperPoint/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/yafeng/anaconda3/envs/SuperPoint/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/yafeng/anaconda3/envs/SuperPoint/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: Cast string to float is not supported
	 [[{{node Cast}} = Cast[DstT=DT_FLOAT, SrcT=DT_STRING, Truncate=false, _device="/device:CPU:0"](arg0)]]
	 [[node OneShotIterator_2 (defined at /home/yafeng/Projects/SuperPoint/superpoint/datasets/base_dataset.py:109)  = OneShotIterator[container="", dataset_factory=_make_dataset_qitaVLF1Dtw[], output_shapes=[[3,3], [?,?,1], [?,?,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], shared_name="", _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
python-BaseException

**Comment by 1962975362** [comment]
why i meet  this issue？ could you give some solutions

**Comment by rpautrat** [comment]
Hi,
What version of Python and Tensorflow are you using?

**Comment by 1962975362** [comment]
Hi, thank you so much for your help.
I have solved most of the errors I encountered during training.
Now we are going to conduct superpoint training on Coco, and the results are as follows. 
(1) Could you please provide your training results for reference, mainly in terms of accuracy and recall rate? Thank you very much
(2) In addition, we do 'Matching Features Demo with Pretrained Weights', input 2 images ,model is the provided sp_v6, it shows ''OSError: SavedModel file does not exist at: /home/ninghua/data/1/liyafeng/SuperPoint/output/saved_models/sp_v6/{saved_model.pbtxt|saved_model.pb}
'', 
![image](https://user-images.githubusercontent.com/45714180/130557776-7f07df60-f6f1-433c-8f1a-068df6609178.png)

**Comment by rpautrat** [comment]
Hi,

(1) Here were my output of the descriptor training:
[11/02/2019 19:45:05 INFO] Iter    0: loss 26.0874, precision 0.0037, recall 0.0077
[11/02/2019 20:09:04 INFO] Iter 5000: loss 5.6488, precision 0.0272, recall 0.0603
[11/02/2019 20:33:28 INFO] Iter 10000: loss 3.6379, precision 0.0486, recall 0.1052
[11/02/2019 20:55:14 INFO] Iter 15000: loss 2.6789, precision 0.0826, recall 0.1772
[11/02/2019 21:15:11 INFO] Iter 20000: loss 2.4092, precision 0.1275, recall 0.2574
[11/02/2019 21:35:08 INFO] Iter 25000: loss 1.6250, precision 0.1916, recall 0.3253
[11/02/2019 21:55:04 INFO] Iter 30000: loss 1.5479, precision 0.2319, recall 0.3723
[11/02/2019 22:15:00 INFO] Iter 35000: loss 1.5123, precision 0.2723, recall 0.4119
[11/02/2019 22:34:56 INFO] Iter 40000: loss 1.4282, precision 0.2930, recall 0.4453
[11/02/2019 22:54:52 INFO] Iter 45000: loss 1.3856, precision 0.2913, recall 0.4706
[11/02/2019 23:14:47 INFO] Iter 50000: loss 1.2886, precision 0.2760, recall 0.4533
[11/02/2019 23:34:43 INFO] Iter 55000: loss 1.4009, precision 0.3084, recall 0.4988
[11/02/2019 23:54:38 INFO] Iter 60000: loss 1.3107, precision 0.3355, recall 0.5177
[11/03/2019 00:14:40 INFO] Iter 65000: loss 1.7048, precision 0.3322, recall 0.5287
[11/03/2019 00:34:35 INFO] Iter 70000: loss 1.0025, precision 0.3433, recall 0.5367
[11/03/2019 00:54:31 INFO] Iter 75000: loss 1.5769, precision 0.3428, recall 0.5448
[11/03/2019 01:14:25 INFO] Iter 80000: loss 1.1283, precision 0.3512, recall 0.5497
[11/03/2019 01:34:21 INFO] Iter 85000: loss 1.3357, precision 0.3420, recall 0.5537
[11/03/2019 01:54:17 INFO] Iter 90000: loss 1.1635, precision 0.3552, recall 0.5550
[11/03/2019 02:14:14 INFO] Iter 95000: loss 0.8720, precision 0.3639, recall 0.5579
[11/03/2019 02:34:11 INFO] Iter 100000: loss 1.0154, precision 0.3488, recall 0.5606
[11/03/2019 02:54:08 INFO] Iter 105000: loss 1.0073, precision 0.3534, recall 0.5673
[11/03/2019 03:14:05 INFO] Iter 110000: loss 1.1623, precision 0.3624, recall 0.5701
[11/03/2019 03:34:08 INFO] Iter 115000: loss 0.9907, precision 0.3594, recall 0.5629
[11/03/2019 03:54:08 INFO] Iter 120000: loss 1.2128, precision 0.3784, recall 0.5711
[11/03/2019 04:14:05 INFO] Iter 125000: loss 1.2846, precision 0.3640, recall 0.5720
[11/03/2019 04:34:02 INFO] Iter 130000: loss 1.1994, precision 0.3616, recall 0.5763
[11/03/2019 04:53:59 INFO] Iter 135000: loss 1.1397, precision 0.3687, recall 0.5797
[11/03/2019 05:13:57 INFO] Iter 140000: loss 1.2604, precision 0.3605, recall 0.5754
[11/03/2019 05:33:54 INFO] Iter 145000: loss 1.4032, precision 0.3711, recall 0.5808
[11/03/2019 05:53:51 INFO] Iter 150000: loss 0.9151, precision 0.3752, recall 0.5823
[11/03/2019 06:13:48 INFO] Iter 155000: loss 1.1427, precision 0.3720, recall 0.5870
[11/03/2019 06:33:46 INFO] Iter 160000: loss 0.9974, precision 0.3686, recall 0.5850
[11/03/2019 06:53:43 INFO] Iter 165000: loss 1.4975, precision 0.3698, recall 0.5883
[11/03/2019 07:13:41 INFO] Iter 170000: loss 1.2266, precision 0.3691, recall 0.5886
[11/03/2019 07:33:39 INFO] Iter 175000: loss 1.3844, precision 0.3749, recall 0.5914
[11/03/2019 07:53:36 INFO] Iter 180000: loss 1.3627, precision 0.3694, recall 0.5789
[11/03/2019 08:13:33 INFO] Iter 185000: loss 1.0469, precision 0.3564, recall 0.5900
[11/03/2019 08:33:31 INFO] Iter 190000: loss 1.3856, precision 0.3791, recall 0.5937
[11/03/2019 08:53:29 INFO] Iter 195000: loss 1.1223, precision 0.3752, recall 0.5937
[11/03/2019 09:13:31 INFO] Iter 200000: loss 1.1352, precision 0.3765, recall 0.5978
[11/03/2019 09:33:33 INFO] Iter 205000: loss 1.0245, precision 0.3596, recall 0.5882
[11/03/2019 09:53:35 INFO] Iter 210000: loss 0.9231, precision 0.3639, recall 0.5945
[11/03/2019 10:13:36 INFO] Iter 215000: loss 0.9667, precision 0.3744, recall 0.5961
[11/03/2019 10:33:38 INFO] Iter 220000: loss 1.0049, precision 0.3757, recall 0.5928
[11/03/2019 10:53:39 INFO] Iter 225000: loss 1.0517, precision 0.3862, recall 0.5946
[11/03/2019 11:13:40 INFO] Iter 230000: loss 0.9133, precision 0.3780, recall 0.5978
[11/03/2019 11:33:41 INFO] Iter 235000: loss 1.2023, precision 0.3734, recall 0.5989
[11/03/2019 11:53:43 INFO] Iter 240000: loss 1.3015, precision 0.3775, recall 0.5998
[11/03/2019 12:13:44 INFO] Iter 245000: loss 0.9483, precision 0.3670, recall 0.5991
[11/03/2019 12:33:46 INFO] Iter 250000: loss 1.0677, precision 0.3916, recall 0.6028
[11/03/2019 12:53:49 INFO] Iter 255000: loss 1.1519, precision 0.3679, recall 0.5959
[11/03/2019 13:13:51 INFO] Iter 260000: loss 1.4319, precision 0.3837, recall 0.6004
[11/03/2019 13:33:52 INFO] Iter 265000: loss 1.1464, precision 0.3803, recall 0.6020
[11/03/2019 13:53:53 INFO] Iter 270000: loss 0.8592, precision 0.3823, recall 0.6057
[11/03/2019 14:13:55 INFO] Iter 275000: loss 1.2274, precision 0.3723, recall 0.6018
[11/03/2019 14:33:57 INFO] Iter 280000: loss 1.2828, precision 0.3765, recall 0.6097
[11/03/2019 14:53:59 INFO] Iter 285000: loss 1.0825, precision 0.3766, recall 0.6072
[11/03/2019 15:14:00 INFO] Iter 290000: loss 1.1391, precision 0.3997, recall 0.6085
[11/03/2019 15:34:02 INFO] Iter 295000: loss 1.2988, precision 0.3893, recall 0.6060
[11/03/2019 15:54:00 INFO] Training finished
[11/03/2019 15:54:03 INFO] Saving checkpoint for iteration #300000

So your recall is good and your precision could maybe be slightly improved.

(2) Did you untar the given pretrained model as suggested in the Readme? Just make sure that your paths are correct.

**Comment by 1962975362** [comment]
thanks a lot , 
During the training of Superpoint, my loss has been maintained at about 2, which is a little different from your results. May I ask whether it is the batch size reason
here is my setting:
data:
    name: 'coco'
    cache_in_memory: false
    validation_size: 96
    labels: outputs/magic_coco  # use your own labels here
    augmentation:
        photometric:
            enable: true
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur']
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.5, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                motion_blur: {max_kernel_size: 3}
        homographic:
            enable: false  # not implemented
    warped_pair:
        enable: true
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            patch_ratio: 0.85
            max_angle: 1.57
            allow_artifacts: true
        valid_border_margin: 3
model:
    name: 'super_point'
    batch_size: 2
    eval_batch_size: 2
    learning_rate: 0.0001
    lambda_d: 0.05
    positive_margin: 1
    negative_margin: 0.2
    lambda_loss: 10000
    detection_threshold: 0.001
    nms: 4
    # top_k: 600
train_iter: 600000
validation_interval: 5000
data_format: 'channels_last'

**Comment by rpautrat** [comment]
Indeed, your loss seems to be almost twice as big as mine. The batch size should not make a difference ( and we used the same one anyway).

It would be interesting to know which loss is contributing the most to the final loss. In my case, the descriptor loss is negligible, and the two detector losses (one per image) are around 0.5. So the detector is contributing the most to the loss. What about your own distribution?

**Comment by rpautrat** [comment]
I am closing this now, feel free to reopen it if necessary.
