### ISSUE TITLE
evaluate the repeatability

### ISSUE THREAD

**Issue by 1962975362** [rpautrat/SuperPoint#224]
hi
 when i do 4) Evaluating the repeatability on HPatches and 5) Validation on MS-COCO

i always show:

2021-07-16 10:49:19.034635: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30509 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:00:0a.0, compute capability: 7.0)
2021-07-16 10:49:19.034817: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 11816 MB memory) -> physical GPU (device: 1, name: Tesla V100-SXM2-32GB, pci bus id: 0000:00:0b.0, compute capability: 7.0)
2021-07-16 10:49:19.035090: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 30509 MB memory) -> physical GPU (device: 2, name: Tesla V100-SXM2-32GB, pci bus id: 0000:00:0c.0, compute capability: 7.0)
[07/16/2021 10:49:22 INFO] Restoring parameters from /home/ninghua/data/1/liyafeng/SuperPoint/output/magic-point_coco/model/last.ckpt-18000
  0%|                                                                                                                                           | 0/1000 [00:00<?, ?it/s]2021-07-16 10:49:30.980658: W tensorflow/core/framework/op_kernel.cc:1250] OP_REQUIRES failed at cast_op.cc:123 : Unimplemented: Cast string to float is not supported
2021-07-16 10:49:30.980747: E tensorflow/core/common_runtime/executor.cc:623] Executor failed to create kernel. Unimplemented: Cast string to float is not supported
         [[{{node Cast}} = Cast[DstT=DT_FLOAT, SrcT=DT_STRING, Truncate=false, _device="/device:CPU:0"](arg0)]]
2021-07-16 10:49:30.981009: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at iterator_ops.cc:947 : Unimplemented: Cast string to float is not supported
         [[{{node Cast}} = Cast[DstT=DT_FLOAT, SrcT=DT_STRING, Truncate=false, _device="/device:CPU:0"](arg0)]]
Traceback (most recent call last):
  File "/home/yafeng/anaconda3/envs/SuperPoint/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/yafeng/anaconda3/envs/SuperPoint/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/yafeng/anaconda3/envs/SuperPoint/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnimplementedError: Cast string to float is not supported
         [[{{node Cast}} = Cast[DstT=DT_FLOAT, SrcT=DT_STRING, Truncate=false, _device="/device:CPU:0"](arg0)]]
         [[{{node OneShotIterator_2}} = OneShotIterator[container="", dataset_factory=_make_dataset_f3rpJ9vjGC0[], output_shapes=[[3,3], [?,?,1], [?,?,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], shared_name="", _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export_detections_repeatability.py", line 42, in <module>
    data = next(test_set)
  File "/home/yafeng/Projects/SuperPoint/superpoint/datasets/base_dataset.py", line 115, in _get_set_generator
    yield self.sess.run(self.tf_next[set_name])
  File "/home/yafeng/anaconda3/envs/SuperPoint/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/yafeng/anaconda3/envs/SuperPoint/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/yafeng/anaconda3/envs/SuperPoint/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/yafeng/anaconda3/envs/SuperPoint/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: Cast string to float is not supported
         [[{{node Cast}} = Cast[DstT=DT_FLOAT, SrcT=DT_STRING, Truncate=false, _device="/device:CPU:0"](arg0)]]
         [[node OneShotIterator_2 (defined at /home/yafeng/Projects/SuperPoint/superpoint/datasets/base_dataset.py:109)  = OneShotIterator[container="", dataset_factory=_make_dataset_f3rpJ9vjGC0[], output_shapes=[[3,3], [?,?,1], [?,?,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], shared_name="", _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

![image](https://user-images.githubusercontent.com/45714180/125886653-fade4e17-7acf-4d95-96b0-efcfb0fc3c8a.png)
  could you give me some advice

**Comment by rpautrat** [comment]
I am closing this issue since it it exactly the same error as in your previous issue https://github.com/rpautrat/SuperPoint/issues/223#issue-945169276.
