### ISSUE TITLE
cuda version

### ISSUE THREAD

**Issue by shanchanggo** [rpautrat/SuperPoint#250]
hello!
I am a student. i want to run your work recently,but has some problems. now i have cuda 11.2 and cudnn 8.1.1,it does not work. is it need cuda 9.0 and cudnn 7.0?
please answer my question! my dear friends!

**Comment by shanchanggo** [comment]
when i run this:python experiment.py train configs/magic-point_shapes.yaml magic-point_synth,
problems happened

**Comment by rpautrat** [comment]
Hi, the cuda and cudnn version depend on your tensorflow version as well.
Maybe you can use this setup, which has been proven to work for this framework: https://github.com/rpautrat/SuperPoint/issues/173#issue-730896838

**Comment by shanchanggo** [comment]
ok ! I will try other tensorflow version,thank you, if have other questions, i will visit you again!

**Comment by shanchanggo** [comment]
hello!   Another problem occurred.

when I run : 
CUDA_VISIBLE_DEVICES=0 TMPDIR=/tmp/ python experiment.py train configs/magic-point_shapes.yaml magic-point_synth

then ,magic-point shape can be downed, but some broke down!   I want to know why.

> 
[05/04/2022 15:13:33 INFO] Start training
2022-05-04 15:13:34.372053: E tensorflow/core/common_runtime/executor.cc:641] Executor failed to create kernel. Invalid argument: Default MaxPoolingOp only supports NHWC on device type CPU
         [[{{node magicpoint/train_tower0/vgg/pool1/MaxPool}}]]
Traceback (most recent call last):
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
         [[{{node magicpoint/train_tower0/vgg/pool1/MaxPool}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "experiment.py", line 160, in <module>
    args.func(config, output_dir, args)
  File "experiment.py", line 97, in _cli_train
    train(config, config['train_iter'], output_dir, pretrained_dir)
  File "experiment.py", line 30, in train
    keep_checkpoints=config.get('keep_checkpoints', 1))
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/superpoint/models/base_model.py", line 313, in train
    options=options, run_metadata=run_metadata)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
         [[node magicpoint/train_tower0/vgg/pool1/MaxPool (defined at /home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/superpoint/models/backbones/vgg.py:28) ]]

Errors may have originated from an input operation.
Input Source operations connected to node magicpoint/train_tower0/vgg/pool1/MaxPool:
 magicpoint/train_tower0/vgg/conv1_2/bn/FusedBatchNorm (defined at /home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/superpoint/models/backbones/vgg.py:14)

Original stack trace for 'magicpoint/train_tower0/vgg/pool1/MaxPool':
  File "experiment.py", line 160, in <module>
    args.func(config, output_dir, args)
  File "experiment.py", line 97, in _cli_train
    train(config, config['train_iter'], output_dir, pretrained_dir)
  File "experiment.py", line 22, in train
    with _init_graph(config) as net:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "experiment.py", line 74, in _init_graph
    n_gpus=n_gpus, **config['model'])
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/superpoint/models/base_model.py", line 122, in __init__
    self._build_graph()
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/superpoint/models/base_model.py", line 264, in _build_graph
    self._train_graph(data)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/superpoint/models/base_model.py", line 188, in _train_graph
    data, Mode.TRAIN, self.config['batch_size'])
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/superpoint/models/base_model.py", line 157, in _gpu_tower
    net_outputs = self._model(shards[i], mode, **self.config)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/superpoint/models/magic_point.py", line 38, in _model
    outputs = net(image)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/superpoint/models/magic_point.py", line 31, in net
    features = vgg_backbone(image, **config)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/superpoint/models/backbones/vgg.py", line 28, in vgg_backbone
    x = tfl.max_pooling2d(x, 2, 2, name='pool1', **params_pool)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/layers/pooling.py", line 311, in max_pooling2d
    return layer.apply(inputs)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1479, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 537, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 634, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 146, in wrapper
    ), args, kwargs)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 446, in converted_call
    return _call_unconverted(f, args, kwargs)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 253, in _call_unconverted
    return f(*args, **kwargs)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/keras/layers/pooling.py", line 248, in call
    data_format=conv_utils.convert_data_format(self.data_format, 4))
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 3756, in max_pool
    name=name)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 5672, in max_pool
    data_format=data_format, name=name)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by shanchanggo** [comment]
version problems?   or?    friends, I need your help!

**Comment by shanchanggo** [comment]
my                  cuda :11.2                     cudnn: 8.1.1                 tensorflow-gpu: 1.14

**Comment by chengyiyi1** [comment]
> 我的 cuda：11.2 cudnn：8.1.1 tensorflow-gpu：1.14

Bro，Does your version work? Look forward to your reply！
