### ISSUE TITLE
HPatches evaluating repeatability 

### ISSUE THREAD

**Issue by shanchanggo** [rpautrat/SuperPoint#252]
Hi! my dear friends, I am sorry to disturb you again.  When I run the follows,error happened!

4) Evaluating the repeatability on HPatches
python export_detections_repeatability.py configs/magic-point_repeatability.yaml magic-point_coco --export_name=magic-point_hpatches-repeatability-v

The error is:
Traceback (most recent call last):
  File "export_detections_repeatability.py", line 33, in <module>
    with experiment._init_graph(config, with_dataset=True) as (net, dataset):
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/ghy/lsc/superpoint/SuperPoint-master/superpoint/experiment.py", line 71, in _init_graph
    dataset = get_dataset(config['data']['name'])(**config['data'])
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/superpoint/datasets/base_dataset.py", line 102, in __init__
    self.dataset = self._init_dataset(**self.config)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/superpoint/datasets/patches_dataset.py", line 40, in _init_dataset
    homographies.append(np.loadtxt(str(Path(path, "H_1_" + str(i)))))
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/numpy/lib/npyio.py", line 961, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 535, in open
    raise IOError("%s not found." % path)
OSError: /home/ghy/lsc/superpoint/data/HPatches/v_artisans/H_1_2 not found.

So what result in it?

**Comment by rpautrat** [comment]
Hi, your path to the HPatches images/homographies is wrong. You should probably check if you correctly downloaded it and where. In your case, the HPatches folder should be located in "/home/ghy/lsc/superpoint/data/".

**Comment by shanchanggo** [comment]
yes,I do it,but some other problems happened! now ,I maybe use my own picture to replace Hpatches!

**Comment by shanchanggo** [comment]
another thing!

if possible,could you transfer your HPatches dataset to me !

**Comment by rpautrat** [comment]
Actually, I just tried downloading again HPatches and I have the standard "H_1_*" as before. Are you sure you used the official [download link](http://icvl.ee.ic.ac.uk/vbalnt/hpatches/hpatches-sequences-release.tar.gz)?

**Comment by shanchanggo** [comment]
oh!&nbsp; &nbsp;it is different.&nbsp; thank you



---Original---
From: "Rémi ***@***.***&gt;
Date: Mon, May 9, 2022 21:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rpautrat/SuperPoint] HPatches evaluating repeatability  (Issue#252)




 
Actually, I just tried downloading again HPatches and I have the standard "H_1_*" as before. Are you sure you used the official download link?
