### ISSUE TITLE
Not found 

### ISSUE THREAD

**Issue by shanchanggo** [rpautrat/SuperPoint#257]
Hi! when I run visualize_random_homograpgy, the error occurred!  why? do dou know?

with tf.Session() as sess:
    for _ in range(10):
        im, wr, m = sess.run([image, warped, mask])
        idx = np.where(np.logical_not(m))
        im[idx] = im[idx] / 2
        plot_imgs([im[..., 0]/255., wr[..., 0]/255.], cmap='gray', titles=['original', 'warped'])

NotFoundError                             Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1355     try:
-> 1356       return fn(*args)
   1357     except errors.OpError as e:

~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1340       return self._call_tf_sessionrun(
-> 1341           options, feed_dict, fetch_list, target_list, run_metadata)
   1342 

~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1428         self._session, options, feed_dict, fetch_list, target_list,
-> 1429         run_metadata)
   1430 

**NotFoundError: /home/ghy/lsc/superpoint/data/COCO/COCO_train2014_000000000071.jpg; No such file or directory
	 [[{{node ReadFile}}]]**

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
<ipython-input-5-6e862df72d4d> in <module>
      1 with tf.Session() as sess:
      2     for _ in range(10):
----> 3         im, wr, m = sess.run([image, warped, mask])
      4         idx = np.where(np.logical_not(m))
      5         im[idx] = im[idx] / 2

~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    948     try:
    949       result = self._run(None, fetches, feed_dict, options_ptr,
--> 950                          run_metadata_ptr)
    951       if run_metadata:
    952         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1171     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1172       results = self._do_run(handle, final_targets, final_fetches,
-> 1173                              feed_dict_tensor, options, run_metadata)
   1174     else:
   1175       results = []

~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1348     if handle is None:
   1349       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1350                            run_metadata)
   1351     else:
   1352       return self._do_call(_prun_fn, handle, feeds, fetches)

~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1368           pass
   1369       message = error_interpolation.interpolate(message, self._graph)
-> 1370       raise type(e)(node_def, op, message)
   1371 
   1372   def _extend_graph(self):

NotFoundError: /home/ghy/lsc/superpoint/data/COCO/COCO_train2014_000000000071.jpg; No such file or directory
	 [[node ReadFile (defined at <ipython-input-4-6df4b5b41fbb>:2) ]]

Original stack trace for 'ReadFile':
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 619, in start
    self.io_loop.start()
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/asyncio/base_events.py", line 442, in run_forever
    self._run_once()
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/asyncio/base_events.py", line 1462, in _run_once
    handle._run()
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/tornado/ioloop.py", line 688, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/tornado/gen.py", line 814, in inner
    self.ctx_run(self.run)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/tornado/gen.py", line 162, in _fake_ctx_run
    return f(*args, **kw)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/tornado/gen.py", line 775, in run
    yielded = self.gen.send(value)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 361, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/tornado/gen.py", line 162, in _fake_ctx_run
    return f(*args, **kw)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/tornado/gen.py", line 162, in _fake_ctx_run
    return f(*args, **kw)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 541, in execute_request
    user_expressions, allow_stdin,
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/tornado/gen.py", line 162, in _fake_ctx_run
    return f(*args, **kw)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 302, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 539, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2867, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2895, in _run_cell
    return runner(coro)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3072, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3263, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/home/ghy/anaconda3/envs/sp/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-6df4b5b41fbb>", line 2, in <module>
    image = tf.image.decode_jpeg(tf.read_file(str(filename)), channels=1)
  File "/home/ghy/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 626, in read_file
    "ReadFile", filename=filename, name=name)
  File "/home/ghy/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/ghy/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ghy/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/ghy/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by shanchanggo** [comment]
the path of jpg is right,  what reason lead to this problem?
