### ISSUE TITLE
try to train, but cannot find some file like this

### ISSUE THREAD

**Issue by junjieAI** [rpautrat/SuperPoint#26]
@rpautrat 
python3 ./superpoint/experiment.py train ./superpoint/configs/magic-point_shapes.yaml magic-point_synth
[12/15/2018 13:59:30 INFO] Running command TRAIN
[12/15/2018 13:59:30 INFO] Number of GPUs detected: 1
[12/15/2018 13:59:32 INFO] Generating tarfile for primitive draw_lines.
Traceback (most recent call last):                             
  File "./superpoint/experiment.py", line 149, in <module>
    args.func(config, output_dir, args)
  File "./superpoint/experiment.py", line 87, in _cli_train
    train(config, config['train_iter'], output_dir)
  File "./superpoint/experiment.py", line 22, in train
    with _init_graph(config) as net:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "./superpoint/experiment.py", line 69, in _init_graph
    dataset = get_dataset(config['data']['name'])(**config['data'])
  File "/home/jie/project/SuperPoint-master/superpoint/datasets/base_dataset.py", line 102, in __init__
    self.dataset = self._init_dataset(**self.config)
  File "/home/jie/project/SuperPoint-master/superpoint/datasets/synthetic_shapes.py", line 126, in _init_dataset
    self.dump_primitive_data(primitive, tar_path, config)
  File "/home/jie/project/SuperPoint-master/superpoint/datasets/synthetic_shapes.py", line 100, in dump_primitive_data
    tar = tarfile.open(tar_path, mode='w:gz')
  File "/usr/lib/python3.5/tarfile.py", line 1575, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.5/tarfile.py", line 1622, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/usr/lib/python3.5/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
TypeError: invalid file: PosixPath('/home/jie/project/SuperPoint-master/DATA_DIR/synthetic_shapes_v6/draw_lines.tar.gz')

**Comment by rpautrat** [comment]
Hi @junjieAI 
The code actually tries to create this file, but I think that the problem comes from the fact that the path doesn't exist. Can you check that the folder `/home/jie/project/SuperPoint-master/DATA_DIR/synthetic_shapes_v6/` really exists?

**Comment by junjieAI** [comment]
@rpautrat 
thanks for your reply, I've checked the folder /home/jie/project/SuperPoint-master/DATA_DIR/synthetic_shapes_v6/ exists, while the file draw_lines.tar.gz can not found

**Comment by rpautrat** [comment]
Ok so maybe it is your version of the package tarfile that doesn't work with PosixPath. Can you try to replace line 100 in `superpoint/datasets/synthetic_shapes.py`: `tar = tarfile.open(tar_path, mode='w:gz')` by this: `tar = tarfile.open(str(tar_path), mode='w:gz')`?

If it still doesn't work, you can also generate the synthetic shapes on-the-fly with the parameter data->on-the-fly set to True in the config file. But the training will be slower then.
