### ISSUE TITLE
I try to run this project with linux,after make install and I run the command "python experiment.py train configs/magic-point_shapes.yaml magic-point_synth",I got an error.

### ISSUE THREAD

**Issue by Gzihao8** [rpautrat/SuperPoint#262]
(/home/mems/new_home/anaconda3/env/superpoint-tensorflow) mems@mems-System-Product-Name:~/new_home/superpoint-tensorflow/SuperPoint-master/superpoint$ python experiment.py train configs/magic-point_shapes.yaml magic-point_synth
[07/01/2022 12:10:46 INFO] Running command TRAIN
[07/01/2022 12:10:46 INFO] Number of GPUs detected: 1
Traceback (most recent call last):
  File "experiment.py", line 160, in <module>
    args.func(config, output_dir, args)
  File "experiment.py", line 97, in _cli_train
    train(config, config['train_iter'], output_dir, pretrained_dir)
  File "experiment.py", line 22, in train
    with _init_graph(config) as net:
  File "/home/mems/new_home/anaconda3/env/superpoint-tensorflow/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "experiment.py", line 71, in _init_graph
    dataset = get_dataset(config['data']['name'])(**config['data'])
  File "/home/mems/new_home/superpoint-tensorflow/SuperPoint-master/superpoint/datasets/base_dataset.py", line 102, in __init__
    self.dataset = self._init_dataset(**self.config)
  File "/home/mems/new_home/superpoint-tensorflow/SuperPoint-master/superpoint/datasets/synthetic_shapes.py", line 126, in _init_dataset
    self.dump_primitive_data(primitive, tar_path, config)
  File "/home/mems/new_home/superpoint-tensorflow/SuperPoint-master/superpoint/datasets/synthetic_shapes.py", line 71, in dump_primitive_data
    temp_dir = Path(os.environ['TMPDIR'], primitive)
  File "/home/mems/new_home/anaconda3/env/superpoint-tensorflow/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'TMPDIR'

**Comment by Gzihao8** [comment]
Can someone teach me how to solve this problem？

**Comment by Gzihao8** [comment]
I suspect that it is the path problem of config, so I changed the relative path of config to the absolute path.
Run the command 
"python experiment.py train /home/mems/new_home/superpoint-tensorflow/SuperPoint-master/superpoint/configs/magic-point_shapes.yaml magic-point_synth
"
But the same error still exists.

**Comment by Gzihao8** [comment]
I solved the problem.As the author answered in other questions.Running in a terminal for example export TMPDIR=/tmp/ before executing the code.

**Comment by rpautrat** [comment]
I am closing this now, since you found the answer in previous issues. Thanks for reminding the solution to others.
