### ISSUE TITLE
step2 error：

### ISSUE THREAD

**Issue by yyyyiiiinnnn** [rpautrat/SuperPoint#299]
0it [00:00, ?it/s]
0it [00:00, ?it/s]2023-07-26 10:08:55.401672: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2023-07-26 10:10:27.157679: E tensorflow/stream_executor/cuda/cuda_blas.cc:698] failed to run cuBLAS routine cublasGemmBatchedEx: CUBLAS_STATUS_EXECUTION_FAILED
2023-07-26 10:10:27.157720: E tensorflow/stream_executor/cuda/cuda_blas.cc:2620] Internal: failed BLAS call, see log for details
Traceback (most recent call last):
  File "/root/miniconda3/envs/superpoint/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    return fn(*args)
  File "/root/miniconda3/envs/superpoint/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1320, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/root/miniconda3/envs/superpoint/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1408, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Blas xGEMMBatched launch failed : a.shape=[26,4,2], b.shape=[26,2,2], m=4, n=2, k=2, batch_size=26
         [[{{node magicpoint/pred_tower0/while/MatMul}}]]
         [[{{node magicpoint/pred_tower0/while/transform_2/ImageProjectiveTransformV2}}]]

Hello! I need your help. Please help me.

**Comment by yyyyiiiinnnn** [comment]
thanks a lot！
