### ISSUE TITLE
Error in extracting Keypoints using homography adaptation

### ISSUE THREAD

**Issue by touranisatyajit** [rpautrat/SuperPoint#31]
Hi, Thanks so much for the well written codebase for the Superpoint network. 
While I was trying to replicate the results for COCO data, There was this error which occurred in the second part of the network(homography adaptation) to generate keypoints for the coco data. 
Below is the attached log of the same. 

Could you please let me know how to fix this issue? Thanks

$ python export_detections.py configs/magic-point_coco_export.yaml magic-point_synth --pred_only --batch_size=5 --export_name=magic-point_coco-export1
[01/03/2019 10:00:30 INFO] Number of GPUs detected: 1
[01/03/2019 10:00:39 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:39 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:39 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:39 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:39 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:39 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:39 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:39 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:39 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:39 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:40 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:40 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:40 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:40 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:40 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:40 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:40 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:40 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:40 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:40 INFO] Scale of 0 disables regularizer.
[01/03/2019 10:00:41 INFO] Restoring parameters from /home/ubuntu/tutorials/SuperPoint/b/magic-point_synth/model.ckpt-200000
0it [00:00, ?it/s]
20126it [1:26:50,  320131it [1:2620136it [1:26:52,  2014120120166i201736581it [2:38:03,  4.15it/s]2019-01-03 12:38:45.290810: E tensorflow/core/lib/jpeg/jpeg_mem.cc:307] Premature end of JPEG data. Stopped at line 56/396
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid JPEG data or crop window, data size 32768
	 [[Node: DecodePng = DecodePng[channels=3, dtype=DT_UINT8, _device="/device:CPU:0"](ReadFile)]]
	 [[Node: IteratorGetNext_2 = IteratorGetNext[output_shapes=[[?,?,1], []], output_types=[DT_FLOAT, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_2)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export_detections.py", line 53, in <module>
    data.append(next(test_set))
  File "/home/ubuntu/tutorials/SuperPoint/superpoint/datasets/base_dataset.py", line 115, in _get_set_generator
    yield self.sess.run(self.tf_next[set_name])
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid JPEG data or crop window, data size 32768
	 [[Node: DecodePng = DecodePng[channels=3, dtype=DT_UINT8, _device="/device:CPU:0"](ReadFile)]]
	 [[Node: IteratorGetNext_2 = IteratorGetNext[output_shapes=[[?,?,1], []], output_types=[DT_FLOAT, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_2)]]

**Comment by touranisatyajit** [comment]
Further Information: I was able to generate .npz(keypoint) files for around ~35000 images but failed for the rest. I believe there are a total of ~80000 images in the coco dataset.

**Comment by thomasstats** [comment]
@touranisatyajit I'm having the same issue, before closing issues can you please explain what you did to fix them.  thanks.

**Comment by thomasstats** [comment]
For those that end up in this same situation, COCO_train2014_000000167126.jpg is corrupted in your coco download.  Seems to be a fairly common issue.  You can get the image uncorrupted from the coco website.

The difficulty in here lies in that the image it's currently processing isn't in numerical order, so I had to add a tf.print() line to see which image was being loaded.
