### ISSUE TITLE
killed problem

### ISSUE THREAD

**Issue by phj128** [rpautrat/SuperPoint#48]
Thanks for your fantastic code.
But I met a problem.
When I ran TMPDIR='/tmp' CUDA_VISIBLE_DEVICES='0' python experiment.py train configs/magic-point_shapes.yaml magic-point_synth
I got:
[03/16/2019 17:35:07 INFO] Start training
[1]    5974 killed     TMPDIR='/tmp' CUDA_VISIBLE_DEVICES='0' python experiment.py train  
How can I solve this ?
Thanks!

**Comment by rpautrat** [comment]
Why did you append the command with "TMPDIR='/tmp' CUDA_VISIBLE_DEVICES='0' "??

**Comment by phj128** [comment]
Because if I just ran "python experiment.py train configs/magic-point_shapes.yaml magic-point_synth"
I will get 

2019-03-16 18:39:42.622346: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
2019-03-16 18:40:08.687863: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5565 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5)
Traceback (most recent call last):
  File "experiment.py", line 154, in <module>
    args.func(config, output_dir, args)
  File "experiment.py", line 91, in _cli_train
    train(config, config['train_iter'], output_dir)
  File "experiment.py", line 24, in train
    with _init_graph(config) as net:
  File "/home/aoc/anaconda3/envs/tf/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "experiment.py", line 70, in _init_graph
    n_gpus = get_num_gpus()
  File "experiment.py", line 64, in get_num_gpus
    return len(os.environ['CUDA_VISIBLE_DEVICES'].split(','))
  File "/home/aoc/anaconda3/envs/tf/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'CUDA_VISIBLE_DEVICES'

**Comment by rpautrat** [comment]
Do you have a GPU with Cuda installed and everything? At worst if CUDA_VISIBLE_DEVICES is still not set, you can always modify the code of the function `get_num_gpus` in `superpoint/experiment.py` by manually setting the number of GPUs that you have.

**Comment by phj128** [comment]
I changed it to "return 1",but it didn't work.
I got the same result.
I have RTX2080 and I installed CUDA10.1 and cudnn.I installed tensorflow1.6 and other things in anaconda.Maybe the version doesn't fit?
