### ISSUE TITLE
Can it be used to evaluate the descriptors of COCO/patches dataset or others?

### ISSUE THREAD

**Issue by zjk15068083791** [rpautrat/SuperPoint#89]
Hi~ @rpautrat . I have a confusion which is as shown in the question. When I tried to evaluate the descriptors of COCO/patches dataset which is produced in the 5th step, I got the following feedback~
And before the code command, I replaced 'hpatches' with 'coco' which is in "configs/superpoint_hpatches.yaml/data/dataset" and replaced '[480, 640]' with '[240, 320]' which is in "configs/superpoint_hpatches.yaml/data/preprocessing/resize".

(superpoint_py3) zhengjinkai@112-Linux:~/SuperPoint/superpoint$ python export_descriptors.py configs/superpoint_hpatches.yaml superpoint_coco --export_name=superpoint_coco-v
export_descriptors.py:23: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
[07/22/2019 10:05:52 INFO] Number of GPUs detected: 1
Traceback (most recent call last):
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 2 but is rank 0 for 'MatMul' (op: 'MatMul') with input shapes: [], [3,3].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export_descriptors.py", line 33, in <module>
    with experiment._init_graph(config, with_dataset=True) as (net, dataset):
  File "/home/zhengjinkai/.conda/envs/superpoint_py3/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/zhengjinkai/SuperPoint/superpoint/experiment.py", line 68, in _init_graph
    dataset = get_dataset(config['data']['name'])(**config['data'])
  File "/home/zhengjinkai/SuperPoint/superpoint/datasets/base_dataset.py", line 108, in __init__
    self.tf_splits[n] = self._get_data(self.dataset, n, **self.config)
  File "/home/zhengjinkai/SuperPoint/superpoint/datasets/patches_dataset.py", line 84, in _get_data
    homographies = homographies.map(_adapt_homography_to_preprocessing)
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 790, in map
    return MapDataset(self, map_func)
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1597, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 486, in add_to_graph
    self._create_definition_if_needed()
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 321, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 338, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1562, in tf_map_func
    ret = map_func(nested_args)
  File "/home/zhengjinkai/SuperPoint/superpoint/datasets/patches_dataset.py", line 75, in _adapt_homography_to_preprocessing
    H = tf.matmul(up_scale, tf.matmul(H, down_scale))
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 2064, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2507, in _mat_mul
    name=name)
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 706, in create_op
    **kwargs)
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3273, in create_op
    compute_device=compute_device)
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3313, in _create_op_helper
    set_shapes_for_outputs(op)
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2501, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2474, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2404, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/home/zhengjinkai/.local/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shape must be rank 2 but is rank 0 for 'MatMul' (op: 'MatMul') with input shapes: [], [3,3].

So, my question is "Can this system be used to evaluate the descriptors of COCO/patches dataset or other datasets?" Could you answer my question? Thank you very much~

**Comment by rpautrat** [comment]
Hi!
Yes, you can use this code to evaluate the descriptors on COCO. Instead of using [240, 320] for the `resize` parameter in the config file `configs/superpoint_hpatches.yaml`, try to use False when evaluating on COCO (as is suggested in the comment). This should hopefully solve your problem.

**Comment by zjk15068083791** [comment]
@rpautrat Thank you very much for your quick reply! I followed your advice, and it indeed made some progress. But the export file(superpoint_coco-v) is empty. Do you know where the problem is? The running results are as follows~


(superpoint_py3) zhengjinkai@112-Linux:~/SuperPoint/superpoint$ python export_descriptors.py configs/superpoint_hpatches.yaml superpoint_coco --export_name=superpoint_coco-v
export_descriptors.py:23: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
[07/22/2019 15:39:09 INFO] Number of GPUs detected: 1
2019-07-22 15:39:10.377078: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-22 15:39:10.555298: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 0 with properties: 
name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:06:00.0
totalMemory: 11.91GiB freeMemory: 11.76GiB
2019-07-22 15:39:10.555327: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
2019-07-22 15:39:10.777002: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11385 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:06:00.0, compute capability: 6.1)
[07/22/2019 15:39:10 INFO] Scale of 0 disables regularizer.
[07/22/2019 15:39:10 INFO] Scale of 0 disables regularizer.
[07/22/2019 15:39:10 INFO] Scale of 0 disables regularizer.
[07/22/2019 15:39:10 INFO] Scale of 0 disables regularizer.
[07/22/2019 15:39:11 INFO] Scale of 0 disables regularizer.
[07/22/2019 15:39:11 INFO] Scale of 0 disables regularizer.
[07/22/2019 15:39:11 INFO] Scale of 0 disables regularizer.
[07/22/2019 15:39:11 INFO] Scale of 0 disables regularizer.
[07/22/2019 15:39:11 INFO] Scale of 0 disables regularizer.
[07/22/2019 15:39:11 INFO] Scale of 0 disables regularizer.
[07/22/2019 15:39:11 INFO] Scale of 0 disables regularizer.
[07/22/2019 15:39:11 INFO] Scale of 0 disables regularizer.
2019-07-22 15:39:11.306007: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
2019-07-22 15:39:11.306193: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 374 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:06:00.0, compute capability: 6.1)
[07/22/2019 15:39:11 INFO] Restoring parameters from /home/zhengjinkai/SuperPoint/EXPER_DIR/superpoint_coco/model.ckpt-170000
  0%|                                                                                                                                                                                                                                                 | 0/600 [00:00<?, ?it/s]

**Comment by rpautrat** [comment]
What `alteration` parameter did you use in your config file? It should be set to 'all' to run on COCO (sorry for not explicitly mention it somewhere)

**Comment by zjk15068083791** [comment]
It works! Thank you so much for your kindness~

**Comment by rpautrat** [comment]
Great! I am happy to have been of some help :)
