### ISSUE TITLE
Input shape axis 0 must equal 400 got shape [100, 120, 160]

### ISSUE THREAD

**Issue by UCRajkumar** [rpautrat/SuperPoint#91]
I ran the following command:  `  python experiment.py train configs/magic-point_shapes.yaml magic-point_synth` and I have 3 GPUs available. If I run with single GPU it works, but when I specify more than 1 GPU in `experiment.py` I get the following type of errors. Is there a way I can change the code so it will run for many GPUs? 

```
experiment.py:141: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
[07/30/2019 13:22:33 INFO] Running command TRAIN
[07/30/2019 13:22:33 INFO] Number of GPUs detected: 3
[07/30/2019 13:23:53 WARNING] From /data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
[07/30/2019 13:25:06 INFO] Extracting archive for primitive draw_lines.
[07/30/2019 13:25:14 INFO] Extracting archive for primitive draw_polygon.
[07/30/2019 13:25:22 INFO] Extracting archive for primitive draw_multiple_polygons.
[07/30/2019 13:25:31 INFO] Extracting archive for primitive draw_ellipses.
[07/30/2019 13:25:39 INFO] Extracting archive for primitive draw_star.
[07/30/2019 13:25:47 INFO] Extracting archive for primitive draw_checkerboard.
[07/30/2019 13:25:56 INFO] Extracting archive for primitive draw_stripes.
[07/30/2019 13:26:02 INFO] Extracting archive for primitive draw_cube.
[07/30/2019 13:26:10 INFO] Extracting archive for primitive gaussian_noise.
[07/30/2019 13:26:26 INFO] Caching data, fist access will take some time.
[07/30/2019 13:26:27 WARNING] From /data/userdata/u.rajkumar/SuperPoint/superpoint/models/homographies.py:166: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
[07/30/2019 13:26:27 INFO] Caching data, fist access will take some time.
[07/30/2019 13:26:28 INFO] Caching data, fist access will take some time.
2019-07-30 13:26:28.067509: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-07-30 13:26:28.936445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties:
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0d:00.0
totalMemory: 11.90GiB freeMemory: 11.74GiB
2019-07-30 13:26:29.564754: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 1 with properties:
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0e:00.0
totalMemory: 11.90GiB freeMemory: 11.74GiB
2019-07-30 13:26:30.205609: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 2 with properties:
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0f:00.0
totalMemory: 11.90GiB freeMemory: 11.74GiB
2019-07-30 13:26:30.223160: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0, 1, 2
2019-07-30 13:27:18.392514: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-30 13:27:18.392599: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 1 2
2019-07-30 13:27:18.392612: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N Y Y
2019-07-30 13:27:18.392618: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 1:   Y N Y
2019-07-30 13:27:18.392624: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 2:   Y Y N
2019-07-30 13:27:18.395050: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11364 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:0d:00.0, compute capability: 6.1)
2019-07-30 13:27:18.704128: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 11364 MB memory) -> physical GPU (device: 1, name: TITAN Xp, pci bus id: 0000:0e:00.0, compute capability: 6.1)
2019-07-30 13:27:18.941690: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 11364 MB memory) -> physical GPU (device: 2, name: TITAN Xp, pci bus id: 0000:0f:00.0, compute capability: 6.1)
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:20 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:21 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:21 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:21 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:21 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:21 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:21 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:21 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:21 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:21 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:21 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:22 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
[07/30/2019 13:27:23 INFO] Scale of 0 disables regularizer.
2019-07-30 13:27:23.674355: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0, 1, 2
2019-07-30 13:27:23.674770: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-30 13:27:23.674785: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 1 2
2019-07-30 13:27:23.674792: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N Y Y
2019-07-30 13:27:23.674797: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 1:   Y N Y
2019-07-30 13:27:23.674802: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 2:   Y Y N
2019-07-30 13:27:23.675613: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11364 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:0d:00.0, compute capability: 6.1)
2019-07-30 13:27:23.675936: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 11364 MB memory) -> physical GPU (device: 1, name: TITAN Xp, pci bus id: 0000:0e:00.0, compute capability: 6.1)
2019-07-30 13:27:23.676131: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 11364 MB memory) -> physical GPU (device: 2, name: TITAN Xp, pci bus id: 0000:0f:00.0, compute capability: 6.1)
[07/30/2019 13:27:32 INFO] Start training
Traceback (most recent call last):
  File "/data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input shape axis 0 must equal 150, got shape [50,120,160,1]
         [[Node: magicpoint/eval_data_sharding/unstack = Unpack[T=DT_FLOAT, axis=0, num=150, _device="/job:localhost/replica:0/task:0/device:CPU:0"](magicpoint/IteratorGetNext)]]
         [[Node: magicpoint/eval_tower2/map/while/box_nms/non_max_suppression/NonMaxSuppressionV2/_1233 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:2", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_779_m...pressionV2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:2"](^_cloopmagicpoint/eval_tower2/map/while/box_nms/Gather_1/_848)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "experiment.py", line 148, in <module>
    args.func(config, output_dir, args)
  File "experiment.py", line 86, in _cli_train
    train(config, config['train_iter'], output_dir)
  File "experiment.py", line 27, in train
    keep_checkpoints=config.get('keep_checkpoints', 1))
  File "/data/userdata/u.rajkumar/SuperPoint/superpoint/models/base_model.py", line 318, in train
    metrics = self.evaluate('validation', mute=True)
  File "/data/userdata/u.rajkumar/SuperPoint/superpoint/models/base_model.py", line 371, in evaluate
    feed_dict={self.handle: self.dataset_handles[dataset]}))
  File "/data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input shape axis 0 must equal 150, got shape [50,120,160,1]
         [[Node: magicpoint/eval_data_sharding/unstack = Unpack[T=DT_FLOAT, axis=0, num=150, _device="/job:localhost/replica:0/task:0/device:CPU:0"](magicpoint/IteratorGetNext)]]
         [[Node: magicpoint/eval_tower2/map/while/box_nms/non_max_suppression/NonMaxSuppressionV2/_1233 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:2", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_779_m...pressionV2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:2"](^_cloopmagicpoint/eval_tower2/map/while/box_nms/Gather_1/_848)]]

Caused by op 'magicpoint/eval_data_sharding/unstack', defined at:
  File "experiment.py", line 148, in <module>
    args.func(config, output_dir, args)
  File "experiment.py", line 86, in _cli_train
    train(config, config['train_iter'], output_dir)
  File "experiment.py", line 21, in train
    with _init_graph(config) as net:
  File "/data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "experiment.py", line 71, in _init_graph
    n_gpus=n_gpus, **config['model'])
  File "/data/userdata/u.rajkumar/SuperPoint/superpoint/models/base_model.py", line 122, in __init__
    self._build_graph()
  File "/data/userdata/u.rajkumar/SuperPoint/superpoint/models/base_model.py", line 265, in _build_graph
    self._eval_graph(data)
  File "/data/userdata/u.rajkumar/SuperPoint/superpoint/models/base_model.py", line 216, in _eval_graph
    tower_metrics = self._gpu_tower(data, Mode.EVAL, self.config['eval_batch_size'])
  File "/data/userdata/u.rajkumar/SuperPoint/superpoint/models/base_model.py", line 142, in _gpu_tower
    shards = self._unstack_nested_dict(data, batch_size*self.n_gpus)
  File "/data/userdata/u.rajkumar/SuperPoint/superpoint/models/base_model.py", line 126, in _unstack_nested_dict
    else tf.unstack(v, num=num, axis=0) for k, v in d.items()}
  File "/data/userdata/u.rajkumar/SuperPoint/superpoint/models/base_model.py", line 126, in <dictcomp>
    else tf.unstack(v, num=num, axis=0) for k, v in d.items()}
  File "/data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1084, in unstack
    return gen_array_ops.unpack(value, num=num, axis=axis, name=name)
  File "/data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8718, in unpack
    "Unpack", value=value, num=num, axis=axis, name=name)
  File "/data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Input shape axis 0 must equal 150, got shape [50,120,160,1]
         [[Node: magicpoint/eval_data_sharding/unstack = Unpack[T=DT_FLOAT, axis=0, num=150, _device="/job:localhost/replica:0/task:0/device:CPU:0"](magicpoint/IteratorGetNext)]]
         [[Node: magicpoint/eval_tower2/map/while/box_nms/non_max_suppression/NonMaxSuppressionV2/_1233 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:2", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_779_m...pressionV2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:2"](^_cloopmagicpoint/eval_tower2/map/while/box_nms/Gather_1/_848)]]

```

any idea how to solve it? (This is when I tried to train with 8 GPUs)

When I tried again with 4, I got the following:

**Comment by rpautrat** [comment]
Hi,

Can you give the full error message and what command you ran exactly? Because here we don't even see where the error happened and what you did to get it...

Please use the triple quote for your error message (```): it will keep the line breaks and make it more readable.

**Comment by UCRajkumar** [comment]
I've put the full error. ALso, to end training of magic point (when precision and recall are converging), should I simply CTRL+C or is there a better way of doing it?

**Comment by UCRajkumar** [comment]
Also, when repeating steps 2 and 3, should i be using a new `--export_name` every time in step 2 or just the same one? And should I be using magic_point_coco instead of magic_point_synth the second time I do step 2?

**Comment by rpautrat** [comment]
Thanks for the full error message. That's an old issue when using multiple GPUs. It is caused by the fact that the validation dataset size (parameter 'data->validation_size' in your config file) is not evenly divisible by your eval_batch_size x num_gpus. In your case I guess that you have a validation_size of 500, an eval_batch_size of 50 and 3 GPUs. Changing your validation_size to 450 should fix the problem.

To end the training, either you know in advance how many iterations you wanted to train and in that case you can specify it in the config file ('train_iter' parameter) or you can also just kill it with CTRL+C, it will save the model with the most recent weights anyway.

If you reuse the same `--export_name` every time, it will just erase the previous one each time. So if you want to keep the previous exports just in case, it might be better to change the name each time. The second time you apply step 2, reuse the name of the model that you trained in the previous step (magic_point_coco or whatever you called it at the time).

**Comment by UCRajkumar** [comment]
Great thank you!
