### ISSUE TITLE
semi-dense to dense

### ISSUE THREAD

**Issue by UCRajkumar** [rpautrat/SuperPoint#97]
I wanted to do the following. Instead of comparing 8x8 cells, I wanted to compare every single pixel. So, I changed the [grid_size to 1 ](https://github.com/rpautrat/SuperPoint/blob/2962dde0687b36779291ea565c334487a89ce7fe/superpoint/models/super_point.py#L15)in the default config and changed the[ distance threshold for positive correspondence ](https://github.com/rpautrat/SuperPoint/blob/2962dde0687b36779291ea565c334487a89ce7fe/superpoint/models/utils.py#L94)to 0, so that it's a pixel to pixel correspondence only. 
However, I'm getting the following error:

```
Traceback (most recent call last):
  File "experiment.py", line 147, in <module>
    args.func(config, output_dir, args)
  File "experiment.py", line 85, in _cli_train
    train(config, config['train_iter'], output_dir)
  File "experiment.py", line 20, in train
    with _init_graph(config) as net:
  File "/data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "experiment.py", line 70, in _init_graph
    n_gpus=n_gpus, **config['model'])
  File "/data/userdata/u.rajkumar/SuperPoint/superpoint/models/base_model.py", line 122, in __init__
    self._build_graph()
  File "/data/userdata/u.rajkumar/SuperPoint/superpoint/models/base_model.py", line 264, in _build_graph
    self._train_graph(data)
  File "/data/userdata/u.rajkumar/SuperPoint/superpoint/models/base_model.py", line 188, in _train_graph
    data, Mode.TRAIN, self.config['batch_size'])
  File "/data/userdata/u.rajkumar/SuperPoint/superpoint/models/base_model.py", line 157, in _gpu_tower
    net_outputs = self._model(shards[i], mode, **self.config)
  File "/data/userdata/u.rajkumar/SuperPoint/superpoint/models/super_point.py", line 40, in _model
    results = net(inputs['image'])
  File "/data/userdata/u.rajkumar/SuperPoint/superpoint/models/super_point.py", line 36, in net
    detections = utils.detector_head(features, **config)
  File "/data/userdata/u.rajkumar/SuperPoint/superpoint/models/utils.py", line 25, in detector_head
    prob, config['grid_size'], data_format='NCHW' if cfirst else 'NHWC')
  File "/data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2278, in depth_to_space
    return gen_array_ops.depth_to_space(input, block_size, data_format, name=name)
  File "/data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 885, in depth_to_space
    data_format=data_format, name=name)
  File "/data/userdata/u.rajkumar/software/anaconda3/envs/SP/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 708, in _apply_op_helper
    (key, op_type_name, attr_value.i, attr_def.minimum))
ValueError: Attr 'block_size' of 'DepthToSpace' Op passed 1 less than minimum 2.
```
I'm guessing I probably have to make a bunch more changes. Any advice on what else I'd need to change?

**Comment by rpautrat** [comment]
With a grid_size of 1, the op depth_to_space (l.24 of utils.py) that caused your error is actually an identity function, so you can just uncomment it.

Otherwise the main problem is that currently the encoder downsamples the image by 8 in width and height (H/8 x W/8) via three max_pooling2d in the VGG encoder. If you do it pixel by pixel, you will have either to remove all the max_pooling2d in the encoder or upsample the spatial dimension in the decoder and descriptor branches to get back again an HxW image. The bi-cubic interpolation of the descriptor branch will then become unnecessary, you can remove it.

So far, it's all the changes that come to my mind, but there might be a few more fixes to make it work. Anyway, you should be aware that with this change your runtime will get worse and this will require a lot more training memory. Basically in the current approach, we manipulate in the descriptor loss tensors of size batch_size x Hc x Wc x Hc x Wc (where Hc=H/8, Wc=W/8 and your original image is of dimension HxW). With your modification you will have it of size batch_size x H x W x H x W, i.e. 64 times bigger than before. Since the current code is already requiring a lot of GPU memory, this would 64 times more memory...

**Comment by UCRajkumar** [comment]
Shouldn't the descriptor loss be Hc x Wc x 256 x batchsize? Why is it Hc^2 x Wc^2 x batchsize?
